---
- name: install httpd
  yum: name=httpd state=installed

- name: place httpd conf file
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf mode=0644 owner=root group=root
  notify: 
    - restart httpd

- name: httpd is running and enabled
  service: name=httpd state=running enabled=yes
