---
- name: set mysql epel repository
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: install MySQL
  yum: name=mysql-community-server state=installed

- name: place mysql conf file
  template: src=my.cnf dest=/etc/my.cnf mode=0644 owner=root group=root
  notify:
    - restart MySQL

- name: start MySQL
  service: name=mysqld state=running enabled=yes
